import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import IntroComponent from '@/components/typeAnimations';
import 'animate.css';

const inter = Inter({ subsets: ['latin'] });
export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className='min-h-screen flex'>
        <div className='w-[50%] align-middle m-auto leading-loose text-center text-3xl animate__animated animate__bounceInDown'>
          <IntroComponent></IntroComponent>
        </div>
      </main>
    </>
  )
}
